### version information

```
pre-commit version: 4.3.0
git --version: git version 2.43.0
sys.version:
    3.12.3 (main, Aug 14 2025, 17:47:21) [GCC 13.3.0]
sys.executable: /home/mateo/blog-DCF/.venv/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
stdout: (none)
stderr:
    fatal: unable to access 'https://github.com/astral-sh/ruff-pre-commit/': Could not resolve host: github.com
```

```
Traceback (most recent call last):
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/store.py", line 207, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/store.py", line 189, in _shallow_clone
    git_cmd('-c', git_config, 'fetch', 'origin', ref, '--depth=1')
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/store.py", line 204, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', '-c', 'protocol.version=2', 'fetch', 'origin', 'v0.6.9', '--depth=1')
return code: 128
stdout: (none)
stderr:
    fatal: unable to access 'https://github.com/astral-sh/ruff-pre-commit/': Could not resolve host: github.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/commands/run.py", line 425, in run
    for hook in all_hooks(config, store)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/repository.py", line 233, in all_hooks
    return tuple(
           ^^^^^^
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/repository.py", line 236, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/repository.py", line 211, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/repository.py", line 177, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/store.py", line 211, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/store.py", line 165, in _new_repo
    make_strategy(directory)
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/store.py", line 209, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/store.py", line 181, in _complete_clone
    git_cmd('fetch', 'origin', '--tags')
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/store.py", line 204, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/mateo/blog-DCF/.venv/lib/python3.12/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
stdout: (none)
stderr:
    fatal: unable to access 'https://github.com/astral-sh/ruff-pre-commit/': Could not resolve host: github.com
```
